GET http://localhost:3001/api/persons 

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/68ae886d6fde78d90636d255

###
DELETE http://localhost:3001/api/persons/68ae86ccc4bec79ab46a551a

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "cristian cbc",
    "number": "44-5-89712"
}